### ISSUE TITLE
Poblem with long menus

### ISSUE THREAD

**Issue by byroncorrales** [duanewilson/bootstrap-fullscreen-menu#1]
The fullscreen modal menu do not cover all the page when you have a menu with several elements.

I suggest to use min-height instead height so solve the problem.

  .fullscreen .modal-dialog {
        min-height: 100%;
    }
    .fullscreen .modal-content {
       min-height: 100%;
    }

**Comment by duanewilson** [comment]
Awesome. Thanks for sharing! I'l incorporate.

**Comment by byroncorrales** [comment]
I reduce my test menu to lest elements, and If use min-height, as I suggested, now the menu do not cover all the page and I needed to go back to height:100%. So I think it is a game to use height:100% or min-height:100% it dependence of the size of your menu. Please make some test, to check what it is the best option for your project.

**Comment by duanewilson** [comment]
Yes, you need both! I had to commit again, so the latest code should work well for both short and long / scrolling menu lengths.

**Comment by byroncorrales** [comment]
Awesome ... Perfect! thanks for add my contribution.  A screenshot of how nice looks your menu http://cl.ly/image/0u3F3o2R3O0A/Snip20150301_11.png

**Comment by duanewilson** [comment]
very cool! like the styling. thanks for helping!
